import { Role } from '@/types';

export const ROLES: Record<string, Role> = {
  ceo: {
    slug: 'ceo',
    name: 'Aria',
    title: 'CEO',
    description: 'Vision, strategy & go/no-go decisions',
    icon: 'Crown',           // from lucide-react
    color: 'indigo',         // tailwind color
    bgLight: 'bg-indigo-50 dark:bg-indigo-900/20',
    bgDark: 'bg-indigo-600',
    text: 'text-indigo-700 dark:text-indigo-300',
    border: 'border-indigo-200 dark:border-indigo-800',
    artifactType: 'Decision Memo',
  },
  coo: {
    slug: 'coo',
    name: 'Dev',
    title: 'COO',
    description: 'Execution, timelines & operations',
    icon: 'ListChecks',
    color: 'emerald',
    bgLight: 'bg-emerald-50 dark:bg-emerald-900/20',
    bgDark: 'bg-emerald-600',
    text: 'text-emerald-700 dark:text-emerald-300',
    border: 'border-emerald-200 dark:border-emerald-800',
    artifactType: 'Execution Plan',
  },
  cfo: {
    slug: 'cfo',
    name: 'Maya',
    title: 'CFO',
    description: 'Financials, unit economics & burn rate',
    icon: 'IndianRupee',
    color: 'amber',
    bgLight: 'bg-amber-50 dark:bg-amber-900/20',
    bgDark: 'bg-amber-600',
    text: 'text-amber-700 dark:text-amber-300',
    border: 'border-amber-200 dark:border-amber-800',
    artifactType: 'Financial Breakdown',
  },
  product: {
    slug: 'product',
    name: 'Kai',
    title: 'Product Lead',
    description: 'User needs, scope & feature priorities',
    icon: 'Layers',
    color: 'violet',
    bgLight: 'bg-violet-50 dark:bg-violet-900/20',
    bgDark: 'bg-violet-600',
    text: 'text-violet-700 dark:text-violet-300',
    border: 'border-violet-200 dark:border-violet-800',
    artifactType: 'PRD-lite',
  },
  marketing: {
    slug: 'marketing',
    name: 'Priya',
    title: 'Marketing Lead',
    description: 'Channels, audience & growth strategy',
    icon: 'Megaphone',
    color: 'rose',
    bgLight: 'bg-rose-50 dark:bg-rose-900/20',
    bgDark: 'bg-rose-600',
    text: 'text-rose-700 dark:text-rose-300',
    border: 'border-rose-200 dark:border-rose-800',
    artifactType: 'Marketing Brief',
  },
} as const;
